[package]
name = "tilelive"
version = "0.1.0"
authors = ["Stepan Kuzmin <to.stepan.kuzmin@gmail.com>"]
edition = "2018"

[dependencies]
url = "2.1.0"
tilelive-core = { path = '../tilelive-core' }
tilelive-postgis = { path = '../tilelive-postgis' }